v1.0.50
1. Mbus rules now include scanning functionality
2. SNMP Rule Scan Function Adds Interface Selection
3. Fixed a bug where the rule configuration export only produced a single entry.

Signed-off-by: Elastel <elastel.group@gmail.com>

diff --git a/update b/update
--- a/update
+++ b/update
@@ -62,7 +62,10 @@ install_lib_if_needed() {
 
         if ! ldconfig -p | grep -q "$lib"; then
                 echo "$lib is NOT installed, installing $pkg ..."
-                apt install -y "$pkg"
+                apt-get install -y "$pkg" || {
+                        echo "Failed to install $pkg."
+                        exit 4
+                }
         fi
 }
 
